spring.application.name=email-assistant


gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-flash-latest:generateContent
gemini.api.key=AIzaSyD_fbaOqkByKwXxrZ3Iu_L_3FrGtPJsIH0